### ISSUE TITLE
How to allow icmp and tcp/udp/sctp at same template

### ISSUE THREAD

**Issue by BurlyLuo** [k8snetworkplumbingwg/multi-networkpolicy-iptables#68]
template details:
```
[root@rowan> 15-kind-multi-networkpolicy-macvlan]# cat 3-multi-networkpolicy-tcp-srcPort81-dstPort81-.yaml 
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/policy-for: macvlan-conf-1 
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.10.0.0/16
        except:
        - 10.10.100.0/24
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 81
  egress:
  - to:
    - ipBlock:
        cidr: 10.10.0.0/16
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 81    
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "eth0",
            "mode": "bridge",
            "ipam": {
                "type": "whereabouts",
                "range": "10.10.0.20-10.10.0.50/16"
            }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: mp1
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    imagePullPolicy: IfNotPresent
    name: nettool
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
  nodeName: cni-multus-worker
---
apiVersion: v1
kind: Pod
metadata:
  name: mp2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    imagePullPolicy: IfNotPresent
    name: nettool
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
  nodeName: cni-multus-worker
[root@rowan> 15-kind-multi-networkpolicy-macvlan]# 

^C[root@rowan> 15-kind-multi-networkpolicy-macvlan]# k exec -it mp1 bash 
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
mp1~$ping 10.10.0.21
PING 10.10.0.21 (10.10.0.21): 56 data bytes
ping: sendto: Operation not permitted
mp1~$curl --local-port 81 10.10.0.21
PodName: mp2 | PodIP: eth0 10.244.171.23/32 net1 10.10.0.21/16
mp1~$curl --local-port 82 10.10.0.21
^C
mp1~$exit
exit
command terminated with exit code 130
[root@rowan> 15-kind-multi-networkpolicy-macvlan]# 
```
if we spec tcp/udp/sctp the icmp will be blocked. 
if with: it can be worked as expected.
```
[root@rowan> 15-kind-multi-networkpolicy-macvlan]# cat 2-icmp-multi-networkpolicy.yaml 
apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/policy-for: macvlan-conf-1 
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.10.0.0/16
        except:
        - 10.10.1.0/24
  egress:
  - to:
    - ipBlock:
        cidr: 10.10.0.0/16
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.0",
            "type": "macvlan",
            "master": "eth0",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "10.10.0.0/16",
                         "rangeStart": "10.10.1.20",
                         "rangeEnd": "10.10.3.50",
                         "gateway": "10.10.0.254"
                    } ]
                ]
            }
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: mpicmp
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf-1
spec:
  containers:
  - image: 192.168.2.100:5000/nettool
    imagePullPolicy: IfNotPresent
    name: alpine
    securityContext:
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
  restartPolicy: Always
[root@rowan> 15-kind-multi-networkpolicy-macvlan]# 
```
so my question is how to  full icmp and l4 protocol.
